# Generated by Django 5.0.2 on 2024-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_list_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='file',
            new_name='source',
        ),
    ]
