# Generated by Django 5.0.3 on 2024-03-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_rename_file_list_source'),
        ('message', '0004_alter_list_section_alter_list_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_files', to='message.list'),
        ),
    ]
