# Generated by Django 5.0.2 on 2024-02-27 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('section', '0002_alter_list_project_alter_list_step_alter_list_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_messages', to='section.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagfes', to=settings.AUTH_USER_MODEL),
        ),
    ]
