# Generated by Django 5.0.2 on 2024-02-25 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_list_status_list_type'),
        ('section', '0003_alter_list_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='project',
        ),
        migrations.RemoveField(
            model_name='list',
            name='receiver',
        ),
        migrations.AddField(
            model_name='list',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_section', to='section.list'),
            preserve_default=False,
        ),
    ]
