# Generated by Django 5.0.2 on 2024-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_list_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
