# Generated by Django 5.0.2 on 2024-02-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('section', '0002_alter_list_project_alter_list_step_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_payment', to='section.list'),
        ),
    ]
