# Generated by Django 5.0.3 on 2024-03-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_alter_list_project_alter_list_user'),
        ('space', '0002_alter_list_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_sections', to='space.list'),
        ),
    ]
