# Generated by Django 5.0.2 on 2024-02-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_list_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
