# Generated by Django 5.0.2 on 2024-03-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='project.list')),
                ('space', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project_spaces', to='space.list')),
            ],
        ),
    ]
