# Generated by Django 5.0.2 on 2024-03-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('project', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='project.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='space',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_spaces', to='space.list'),
        ),
    ]
