# Generated by Django 5.0.2 on 2024-03-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_list_project_alter_list_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='image',
            new_name='source',
        ),
    ]
