# Generated by Django 5.0.2 on 2024-03-07 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_rename_image_list_source'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='space',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_images', to='space.list'),
        ),
    ]
