# Generated by Django 5.0.2 on 2024-02-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default=0)),
                ('content_size', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('project_period', models.IntegerField(default=0)),
                ('recruitment_content', models.IntegerField(default=0)),
                ('recruitment_number', models.CharField(max_length=255)),
                ('recruitment_period', models.IntegerField(default=0)),
                ('space_type', models.IntegerField(default=0)),
                ('year_designation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
