# Generated by Django 5.0.2 on 2024-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_list_content_size_alter_list_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
