# Generated by Django 5.0.2 on 2024-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_list_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='progress',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Undefined'), (1, '提案'), (2, '選定'), (3, '承諾'), (4, '仮払い'), (5, '広告物発送'), (6, '広告物受け取り'), (7, '開始報告'), (8, '経過報告'), (9, '終了報告'), (10, '支払い'), (11, 'レビュー')], default=1),
        ),
    ]
