# Generated by Django 5.0.2 on 2024-02-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_rename_space_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
