# Generated by Django 5.0.2 on 2024-02-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_list_main_pr_target_list_main_service_list_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='website_url',
            field=models.CharField(max_length=100),
        ),
    ]
