# Generated by Django 5.0.2 on 2024-02-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_list_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='message',
            new_name='main_message',
        ),
    ]
