# Generated by Django 5.0.2 on 2024-03-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_message_list_main_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='avatar',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
