# Generated by Django 5.0.2 on 2024-03-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_list_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
