# Generated by Django 5.0.2 on 2024-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_list_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='list',
            name='website_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
